import {PRO, CLN} from '../../../config/gameConstants';

export const tiles = [
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN],
    [CLN,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,CLN],
    [CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN],
    [CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN],
    [CLN,PRO,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN],
    [CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN],
    [CLN,CLN,PRO,PRO,CLN,CLN,CLN,CLN,CLN,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,CLN],
    [CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN],
    [CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN],
    [CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN],
    [CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,PRO,PRO,PRO,CLN],
    [CLN,CLN,CLN,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,CLN,PRO,CLN,CLN,CLN],
    [CLN,CLN,CLN,CLN,CLN,CLN,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,PRO,CLN,CLN,CLN]
];